name: Build and Test


on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v3

      
      - name: Echo a message
        run: echo "Hello, GitHub Actions!"
